services:
  custom-blinko-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: custom-blinko-mcp-server
    restart: unless-stopped
    environment:
      - HOST_IP=${HOST_IP}
      - SSE_PORT=${SSE_PORT}
      - BLINKO_DOMAIN=${BLINKO_DOMAIN}
      - BLINKO_API_KEY=${BLINKO_API_KEY}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    ports:
      - "${SSE_PORT}:${SSE_PORT}"
    volumes:
      - ./logs:/app/logs
    networks:
      - custom-blinko-network

networks:
  custom-blinko-network:
    driver: bridge